version: '3.8'

services:
  back-proxy:
    build:
      context: ./back-proxy
      dockerfile: Dockerfile
      args:
        - JAR_FILE=back-proxy-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"

  teams:
    build:
      context: ./teams
      dockerfile: Dockerfile
      args:
        - JAR_FILE=teams-0.0.1-SNAPSHOT.jar
    ports:
      - "8082:8082"

  security:
    build:
      context: ./security
      dockerfile: Dockerfile
      args:
        - JAR_FILE=security-0.0.1-SNAPSHOT.jar
    ports:
      - "9001:9001"
