  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Real Madrid', 'La Liga', 'España');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'FC Barcelona', 'La Liga', 'España');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Manchester United', 'Premier League', 'Inglaterra');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Liverpool FC', 'Premier League', 'Inglaterra');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Juventus FC', 'Serie A', 'Italia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'AC Milan', 'Serie A', 'Italia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Bayern Munich', 'Bundesliga', 'Alemania');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Borussia Dortmund', 'Bundesliga', 'Alemania');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Paris Saint-Germain', 'Ligue 1', 'Francia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Olympique de Marseille', 'Ligue 1', 'Francia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'FC Porto', 'Primeira Liga', 'Portugal');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Sporting CP', 'Primeira Liga', 'Portugal');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Ajax Amsterdam', 'Eredivisie', 'Países Bajos');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Feyenoord', 'Eredivisie', 'Países Bajos');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Celtic FC', 'Scottish Premiership', 'Escocia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Rangers FC', 'Scottish Premiership', 'Escocia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Galatasaray SK', 'Süper Lig', 'Turquía');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Fenerbahçe SK', 'Süper Lig', 'Turquía');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'FC Zenit Saint Petersburg', 'Premier League Rusa', 'Rusia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Spartak Moscow', 'Premier League Rusa', 'Rusia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'SL Benfica', 'Primeira Liga', 'Portugal');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Besiktas JK', 'Süper Lig', 'Turquía');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'SSC Napoli', 'Serie A', 'Italia');
  INSERT INTO TEAMS (id, name, league, country) VALUES (teams_seq.NEXTVAL, 'Atlético Madrid', 'La Liga', 'España');
